/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import bancodemidias.Imagem;
import bancodemidias.ListaDeMidias;
import bancodemidias.Midia;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ketrin d. Vargas, Marina B. Otokovieski, Rafael Souza
 */

public class TelaPrincipalFrame extends javax.swing.JFrame {

    private static ListaDeMidias listMidia;

    /**
     * Creates new form TelaPrincipalFrame
     */
    
    public TelaPrincipalFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); 
        try{
            listMidia = new ListaDeMidias();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro em lista de midia"); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        ajuda = new javax.swing.JMenu();
        comoUsar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        sobreOSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco de Mídias");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Imagem", "Música", "Filme" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 257, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        ajuda.setText("Ajuda");

        comoUsar.setText("Como Usar");
        comoUsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comoUsarActionPerformed(evt);
            }
        });
        ajuda.add(comoUsar);

        jMenuBar1.add(ajuda);

        jMenu4.setText("Sobre");

        sobreOSistema.setText("Informações do Sistema");
        sobreOSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreOSistemaActionPerformed(evt);
            }
        });
        jMenu4.add(sobreOSistema);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comoUsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comoUsarActionPerformed
        JOptionPane.showMessageDialog(jMenuBar1, "Acesse as abas do menu superior Cadastros para realizar o cadastro de mídias."
                + "\nAcesse as abas do menu superior Mídias para visualizar as mídias cadastradas."
                + "\nPara saber mais sobre o sistema acesse a aba Sobre");
    }//GEN-LAST:event_comoUsarActionPerformed

    private void sobreOSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreOSistemaActionPerformed
        JOptionPane.showMessageDialog(jMenuBar1, "Bem-Vindo ao  Sistema Banco de Mídias"
                + "\nO presente sistema tem como propósito cadastrar, alterar, excluir e visualizar mídias."
                + "\nVocê pode consultar suas mídias por: Título ou Data."
                + "\nEm casos de filmes e músicas a busca também pode ser feita por Gênero."
                + "\nQuaisquer dúvidas entre em contato com a equipe de desenvolvimento :D");
    }//GEN-LAST:event_sobreOSistemaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String indice = jComboBox1.getSelectedItem().toString();
        switch (indice) {
            case "Imagem":
                CadastroVisualizacaoImagem Imagem = null;
        try {
            Imagem = new CadastroVisualizacaoImagem(listMidia);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                jDesktopPane1.add(Imagem);                
                Imagem.setVisible(true);
               
                break;
            case "Música":
                CadastroVisualizacaoMusica Musica = null;
        try {
            Musica = new CadastroVisualizacaoMusica(listMidia);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                jDesktopPane1.add(Musica);
                Musica.setVisible(true);
               
                break;
            case "Filme":
                  CadastroVisualizacaoFilme Filme = null;
        try {
            Filme = new CadastroVisualizacaoFilme();
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(TelaPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                  jDesktopPane1.add(Filme);
                  Filme.setVisible(true);
                
                break;
        }      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFrame().setVisible(true);
            }
        });
    }
    
    public static boolean editar(int id, Midia m){
        return listMidia.editar(id, m);
    }
    
    public static boolean adicionar(Midia m){
        return listMidia.adiciona(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem comoUsar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem sobreOSistema;
    // End of variables declaration//GEN-END:variables
}
